# Generated by Django 5.2.7 on 2026-06-18 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('jobs', '0003_alter_job_options_job_application_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('REVIEWED', 'Reviewed'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired')], default='APPLIED', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'applicant')},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_1508e0_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applied_at'], name='application_applied_06e426_idx'),
        ),
    ]
