# Generated by Django 5.2.7 on 2026-06-16 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('FRESHER', 'Fresher'), ('JUNIOR', 'Junior'), ('MID_LEVEL', 'Mid Level'), ('SENIOR', 'Senior')], default='FRESHER', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills'),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancy_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='jobs_job_locatio_8b2f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['employment_type'], name='jobs_job_employm_743f88_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active'], name='jobs_job_is_acti_b6ae73_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='jobs_job_created_1b3a4d_idx'),
        ),
    ]
